version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    entrypoint: sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS clientservicedb; CREATE DATABASE IF NOT EXISTS carservicedb;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "

  yaakoub-eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    expose:
      - '8761'

  yaakoub-apigateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    expose:
      - '8888'
    depends_on:
      yaakoub-eureka-server:
        condition: service_started

  yaakoub-client-service:
    build:
      context: ./EurekaClient
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - '8081'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/clientservicedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_started
      yaakoub-eureka-server:
        condition: service_started

  yaakoub-car-service:
    build:
      context: ./carservice
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    expose:
      - '8082'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/carservicedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_started
      yaakoub-eureka-server:
        condition: service_started

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8088:80"